// Generated by CoffeeScript 1.6.2
/*
 runs through all the nodes, and evaluates them
*/


(function() {
  var Runner;

  Runner = (function() {
    /*
    */
    function Runner() {
      this._evaluators = [];
      this._load();
    }

    /*
    */


    /*
    */


    Runner.prototype.run = function(node, context, next) {
      var _this = this;

      return node.traverse((function(child, next) {
        return _this._run(child, context, next);
      }), next);
    };

    /*
    */


    Runner.prototype._run = function(node, context, next) {
      var evaluator, _i, _len, _ref;

      _ref = this._evaluators;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        evaluator = _ref[_i];
        if (evaluator.test(node)) {
          return evaluator.run(node, context, next);
        }
        next();
      }
    };

    /*
    */


    Runner.prototype._load = function() {};

    return Runner;

  })();

}).call(this);
