// Generated by CoffeeScript 1.6.2
/*
 calls a task
*/


(function() {
  var CallExpression, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CallExpression = (function(_super) {
    __extends(CallExpression, _super);

    function CallExpression() {
      _ref = CallExpression.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    return CallExpression;

  })(require("./base"));

  module.exports = CallExpression;

}).call(this);
