// Generated by CoffeeScript 1.6.2
(function() {
  var Base;

  Base = (function() {
    function Base(all) {
      this.all = all;
    }

    Base.prototype.test = function(node) {
      return false;
    };

    Base.prototype.run = function(node, context, next) {
      return next();
    };

    return Base;

  })();

  module.exports = Base;

}).call(this);
