// Generated by CoffeeScript 1.6.2
(function() {
  var Base;

  Base = (function() {
    /*
     pass all the evaluators
    */
    function Base(all) {
      this.all = all;
      this._commands = all.commands;
    }

    /*
     tests whether a node is runnable
    */


    Base.prototype.test = function(node) {
      return false;
    };

    /*
     runs the node & the context
    */


    Base.prototype.run = function(node, context, next) {
      return next();
    };

    return Base;

  })();

  module.exports = Base;

}).call(this);
