// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, type, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  /*
   runs a command
  */


  Evaluator = (function(_super) {
    __extends(Evaluator, _super);

    function Evaluator() {
      _ref = Evaluator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Evaluator.prototype.run = function(node, context, next) {
      var command;

      command = node.name || node.value;
      return this._commands.execute(command, node, context, function(err) {
        return next(err, false);
      });
    };

    /*
    */


    Evaluator.prototype.test = function(node) {
      return !!node.name || type(node.value) === "string";
    };

    return Evaluator;

  })(require("./base"));

  module.exports = Evaluator;

}).call(this);
