// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, type, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  type = require("type-component");

  /*
   runs a function
  */


  Evaluator = (function(_super) {
    __extends(Evaluator, _super);

    function Evaluator() {
      _ref = Evaluator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Evaluator.prototype.run = function(node, context, next) {
      var e;

      try {
        if (node.value.length === 1) {
          node.value.call(context, context);
          return next();
        } else {
          return node.value.call(context, context, next);
        }
      } catch (_error) {
        e = _error;
        return next(e);
      }
    };

    /*
    */


    Evaluator.prototype.test = function(node) {
      return type(node.value) === "function";
    };

    return Evaluator;

  })(require("./base"));

  module.exports = Evaluator;

}).call(this);
