// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Evaluator = (function(_super) {
    __extends(Evaluator, _super);

    function Evaluator() {
      _ref = Evaluator.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Evaluator.prototype.run = function(node, context, next) {};

    return Evaluator;

  })(require("./base"));

  module.exports = Evaluator;

}).call(this);
