// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluator, evaluators;

  evaluators = {
    def: require("./def"),
    task: require("./task"),
    fn: require("./fn")
  };

  /*
   runs through all the nodes, and evaluates them
  */


  Evaluator = (function() {
    /*
    */
    function Evaluator() {
      this._evaluators = [];
      this.init();
    }

    /*
    */


    Evaluator.prototype.init = function() {
      this._evaluators.push(new evaluators.def(this));
      this._evaluators.push(new evaluators.task(this));
      return this._evaluators.push(new evaluators.fn(this));
    };

    /*
    */


    Evaluator.prototype.run = function(node, context, next) {
      var _this = this;

      return node.traverse((function(child, next) {
        return _this._run(child, context, next);
      }), next);
    };

    /*
    */


    Evaluator.prototype._run = function(node, context, next) {
      var evaluator, _i, _len, _ref;

      _ref = this._evaluators;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        evaluator = _ref[_i];
        if (evaluator.test(node)) {
          return evaluator.run(node, context, next);
        }
        next();
      }
    };

    return Evaluator;

  })();

}).call(this);
