// Generated by CoffeeScript 1.6.2
(function() {
  var Evaluators, evaluators;

  evaluators = {
    def: require("./def"),
    call: require("./call"),
    fn: require("./fn")
  };

  /*
   runs through all the nodes, and evaluates them
  */


  Evaluators = (function() {
    /*
    */
    function Evaluators(commands) {
      this.commands = commands;
      this._evaluators = [];
      this.init();
    }

    /*
    */


    Evaluators.prototype.init = function() {
      this._evaluators.push(new evaluators.fn(this));
      this._evaluators.push(new evaluators.def(this));
      return this._evaluators.push(new evaluators.call(this));
    };

    /*
    */


    Evaluators.prototype.run = function(node, context, next) {
      var _this = this;

      return node.traverse((function(child, next) {
        return _this._run(child, context, next);
      }), next);
    };

    /*
    */


    Evaluators.prototype._run = function(node, context, next) {
      var evaluator, _i, _len, _ref;

      _ref = this._evaluators;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        evaluator = _ref[_i];
        if (evaluator.test(node)) {
          return evaluator.run(node, context, next);
        }
      }
      return next();
    };

    return Evaluators;

  })();

  module.exports = Evaluators;

}).call(this);
