// Generated by CoffeeScript 1.6.2
(function() {
  var Commands, comerr;

  comerr = require("comerr");

  /*
  */


  Commands = (function() {
    /*
    */
    function Commands() {
      this._commands = {};
    }

    /*
    */


    Commands.prototype.describe = function() {
      var desc, key;

      desc = [];
      for (key in this._commands) {
        desc.push(this._commands[key].options);
      }
      return desc;
    };

    /*
    */


    Commands.prototype.register = function(options, listener) {
      return this._commands[options.name] = {
        listener: listener,
        options: options
      };
    };

    /*
    */


    Commands.prototype.execute = function(name, node, context, callback) {
      var ops;

      if (!(ops = this._commands[name])) {
        return callback(new comerr.NotFound("command \"" + name + "\" not found"));
      }
      return ops.listener.call(this, node, context, callback);
    };

    return Commands;

  })();

  module.exports = Commands;

}).call(this);
