// Generated by CoffeeScript 1.6.2
(function() {
  var Commands, comerr;

  comerr = require("comerr");

  /*
  */


  Commands = (function() {
    /*
    */
    function Commands() {
      this._commands = {};
    }

    /*
    */


    Commands.prototype.register = function(name, listener) {
      return this._commands[name] = listener;
    };

    /*
    */


    Commands.prototype.execute = function(name, node, context, callback) {
      var listener;

      if (!(listener = this._commands[name])) {
        return callback(new comerr.NotFound("command \"" + name + "\" not found"));
      }
      return listener.call(this, node, context, callback);
    };

    return Commands;

  })();

  module.exports = Commands;

}).call(this);
